version: '3.2'
services:
  registry:
    image: registry
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/registry
    container_name: registry