version: '3.2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./conf
        target: /etc/gitlab
      - type: bind
        source: ./logs
        target: /var/log/gitlab
      - type: bind
        source: ./data
        target: /var/opt/gitlab
    container_name: gitlab
