version: '3.2'
services:
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./data
        target: /nexus-data
    container_name: nexus