version: '3.2'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - type: bind
        source: ./data
        target: /var/jenkins_home
    container_name: jenkins
