version: '3.7'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-cpp-ce
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./data
        target: /var/opt/jfrog/artifactory
    container_name: artifactory